// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_BaseTroopEvents","status":true,"description":"v1.01 Enabling this plugin will cause all troops to have\r\nevents occur in every fight.","parameters":{"Base Troop ID":"1"}},
{"name":"YEP_EquipCore","status":true,"description":"v1.17 Allows for the equipment system to be more flexible to\r\nallow for unique equipment slots per class.","parameters":{"---General---":"","Text Align":"center","Finish Command":"Finish","Remove Text":"Remove","Remove Icon":"16","Empty Text":"<Empty>","Empty Icon":"16","---Rules---":"","Non-Removable Types":"1","Non-Optimized Types":"5"}},
{"name":"Cv2_DeathCommonEvent","status":true,"description":"[v1.2.0] Calls a Common Event on character death.","parameters":{"DCE Fallthrough":"false","All Ally Dead DCE":"0","All Enemy Dead DCE":"0","Any Ally DCE":"0","Any Enemy DCE":"0"}}
];
